<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS03_Qpass</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3b221fca-a2c8-4818-b581-649d2f147908</testSuiteGuid>
   <testCaseLink>
      <guid>e6a13599-11d7-4453-89c7-3ea8d90528f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC03_Qpass</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f1b90421-d445-45a0-acc0-2eb1851fa555</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TC03_Qpass</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f1b90421-d445-45a0-acc0-2eb1851fa555</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Email</value>
         <variableId>70f0ce3b-e9a0-4c0b-8f9e-c40a8a521db5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f1b90421-d445-45a0-acc0-2eb1851fa555</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Result</value>
         <variableId>c485c211-fb4c-4de5-a68a-dd44e94c09c0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
