<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thanh ton 718.250  (CoD)</name>
   <tag></tag>
   <elementGuidId>c4f27ed1-73c9-4035-9cb4-81a7df1ec1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='purchase']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#purchase</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9079f78a-1bc7-417d-bf8d-367b7412f689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purchase</value>
      <webElementGuid>d343abd3-213e-4de4-836f-55dc99dc52cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2eab2a1b-c354-4a38-b853-d6cdfee795c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-gray-44 btn-continue btn-order btn-cart-confirm-order</value>
      <webElementGuid>9113be91-1597-40d1-a0d1-e8952b8f60c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thanh toán 718.250 ₫ (CoD)</value>
      <webElementGuid>75363b33-5fb4-4fa2-92b3-0d0bd898683b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purchase&quot;)</value>
      <webElementGuid>833b42a6-ad93-435b-ba40-ae856bc8ae24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='purchase']</value>
      <webElementGuid>126c8a19-f5bd-4b4c-94ae-c731598af9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step3']/div[3]/div/button</value>
      <webElementGuid>f70193e3-610a-411b-96fb-1fb21125c573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển khoản trực tiếp'])[3]/following::button[1]</value>
      <webElementGuid>4fe04940-17c8-408a-8689-7d1b3688192a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chuyển khoản trực tiếp'])[2]/following::button[1]</value>
      <webElementGuid>482ef680-c514-429e-a3fd-1eb1c25b2e03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán'])[3]/preceding::button[1]</value>
      <webElementGuid>e3a27c01-a6a2-4181-b431-c1c1c9780215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>6b71746c-cbe5-42db-ae5e-4ff8a7c47fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'purchase' and @type = 'submit' and (text() = 'Thanh toán 718.250 ₫ (CoD)' or . = 'Thanh toán 718.250 ₫ (CoD)')]</value>
      <webElementGuid>08e68602-6070-48a2-9687-d83d4f17b7f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
