<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vui lng chn Phng thc vn chuyn</name>
   <tag></tag>
   <elementGuidId>74cf0e9f-903a-4177-96d4-8da3a2efb9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shippingMethods</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shippingMethods']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab1ad8de-a9be-421a-a27b-3055761ea2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shippingMethods</value>
      <webElementGuid>f131e36a-92af-41a5-a731-ca5faa7c558d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Vui lòng chọn Phương thức vận chuyển
</value>
      <webElementGuid>28d94635-8aed-4650-8b7e-86bad628b4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shippingMethods&quot;)</value>
      <webElementGuid>f11a7b8f-3c4b-4684-b8cd-08a136de03b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='shippingMethods']</value>
      <webElementGuid>bc51c8cb-662a-48b1-a8e5-d58c59859554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='checkout-delivery-address']/div/div/div[2]/div[2]/div</value>
      <webElementGuid>0d82ce22-b6f8-4a28-9e3e-89b38842fd5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phương thức vận chuyển'])[1]/following::div[2]</value>
      <webElementGuid>b3aa7d81-c216-47ed-bdc1-dd4363d9de42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quà tặng'])[2]/following::div[4]</value>
      <webElementGuid>a865bdc5-c2fb-4c5d-8349-fb31e341cb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phương thức thanh toán'])[1]/preceding::div[1]</value>
      <webElementGuid>f2110517-251b-466b-a1dc-a0c3bc134e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thanh toán khi nhận hàng'])[2]/preceding::div[2]</value>
      <webElementGuid>ffb47811-f5dc-4fe1-9f71-7cc09b47ccef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vui lòng chọn Phương thức vận chuyển']/parent::*</value>
      <webElementGuid>f1dff3d8-3fd6-4afe-a139-bc0388385b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[2]/div</value>
      <webElementGuid>c170fcf7-c589-43ac-90f3-30adb298653c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'shippingMethods' and (text() = '
Vui lòng chọn Phương thức vận chuyển
' or . = '
Vui lòng chọn Phương thức vận chuyển
')]</value>
      <webElementGuid>1fae8ab3-e497-4ff7-a14e-930e62ab44c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
