<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_NewAddressForm.Email</name>
   <tag></tag>
   <elementGuidId>b0393c94-775d-404e-8276-0c418a3ad7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NewAddressForm_Email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewAddressForm_Email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34b4dcdb-6c31-40d6-b149-1a41410548e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập Email</value>
      <webElementGuid>7f19dac2-2bae-4e36-835f-4060ec9eb4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebf6b4f6-f879-4324-93a2-3aef59755e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewAddressForm_Email</value>
      <webElementGuid>b7b3f99a-3905-4edd-82a9-0622f4d480c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAddressForm.Email</value>
      <webElementGuid>4c4905fe-28a9-4a2f-9c71-cfd552baa53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAddressForm_Email&quot;)</value>
      <webElementGuid>c55f13ff-3690-4572-a5e3-dda5c203e395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NewAddressForm_Email']</value>
      <webElementGuid>34b7d72a-4fc6-4091-943c-fcc1942887ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step']/div[3]/div/div[8]/div/input</value>
      <webElementGuid>bad8f8ef-daa2-427d-a3d3-76c9ff934f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>c1f2ce96-8fb6-42b1-80e0-12437aedb1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nhập Email' and @type = 'text' and @id = 'NewAddressForm_Email' and @name = 'NewAddressForm.Email']</value>
      <webElementGuid>497fd30b-1371-4a20-9038-420fce226c90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
