<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NewAddressForm.AddressLine1</name>
   <tag></tag>
   <elementGuidId>23619025-ba62-4cd5-9c04-8ee823360967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NewAddressForm_AddressLine1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewAddressForm_AddressLine1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e339bf98-2511-45d8-9c11-0813225af0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa6bda2a-ea00-4a23-9f94-5bb78ee40d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Vd: 64 đường Hiệp Bình</value>
      <webElementGuid>b100851a-6db7-412c-b9a7-4c8c00da9da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>15d89524-0551-4ac0-8a2d-449422548806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The AddressLine1 field is required.</value>
      <webElementGuid>792357fd-92d8-4761-bf5d-a93541a28dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewAddressForm_AddressLine1</value>
      <webElementGuid>1cb5a88e-01eb-4571-b82c-9f20053fb281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAddressForm.AddressLine1</value>
      <webElementGuid>7c27d676-f951-4fb5-b5fa-9f68085ba15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAddressForm_AddressLine1&quot;)</value>
      <webElementGuid>4443690e-d223-431d-b4f2-07af53d4c476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NewAddressForm_AddressLine1']</value>
      <webElementGuid>87d14b76-1ddc-4d80-82fb-30c551887bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step']/div[3]/div/div[7]/div/input</value>
      <webElementGuid>1e9dcea3-3364-4448-9747-e57e290288ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>2be74a7c-5040-47c8-ab8d-380f3dc38ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Vd: 64 đường Hiệp Bình' and @id = 'NewAddressForm_AddressLine1' and @name = 'NewAddressForm.AddressLine1']</value>
      <webElementGuid>7ddcacd9-4752-43de-ade0-dc7dd5bdf720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
