<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NewAddressForm.ContactName</name>
   <tag></tag>
   <elementGuidId>b4c01362-9e28-48a4-b250-9e96c9fc8317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NewAddressForm_ContactName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewAddressForm_ContactName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbe00120-dc47-4dbe-adfe-981efd790e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập Họ tên</value>
      <webElementGuid>c4923c3c-c4c0-4960-bfdc-2fea90060524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e39f0cb-636e-4ea6-918f-a110db43dfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2305edf1-d6b2-47c0-a11d-39acff7cb82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ContactName field is required.</value>
      <webElementGuid>b3c79631-6257-4004-8d5d-c54c96d89a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewAddressForm_ContactName</value>
      <webElementGuid>fc6e479d-4cc4-43c3-bdd4-c9cec06f4272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAddressForm.ContactName</value>
      <webElementGuid>ec7f6902-c939-43fb-a641-ded93386a53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAddressForm_ContactName&quot;)</value>
      <webElementGuid>19415755-9f8a-44b8-bb33-95398003e85e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NewAddressForm_ContactName']</value>
      <webElementGuid>572ab405-5b01-4524-8a68-7d2f9ef6b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step']/div[3]/div/div[2]/div/input</value>
      <webElementGuid>89f8b5ae-15eb-4432-a4f5-680d5f330532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div[2]/div/input</value>
      <webElementGuid>4948c2d4-406c-416a-9a13-08047b4fa5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Nhập Họ tên' and @type = 'text' and @id = 'NewAddressForm_ContactName' and @name = 'NewAddressForm.ContactName']</value>
      <webElementGuid>c5e14abe-e688-4749-9dc0-345271283634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
