<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Chn PhngXPhng BiPhng Nht TnPhng Ph T_946e27</name>
   <tag></tag>
   <elementGuidId>d6d9abe3-9476-4b52-b4a8-e02c7b71ffde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewAddressForm_WardId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NewAddressForm_WardId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7931cbe-9651-48c8-bb00-9e5912502d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewAddressForm_WardId</value>
      <webElementGuid>11598237-1951-4b78-866e-cdb98cb1091e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAddressForm.WardId</value>
      <webElementGuid>504dfdce-7f93-444c-8998-3b26dc79f261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn Phường/XãPhường BưởiPhường Nhật TânPhường Phú ThượngPhường Quảng AnPhường Thụy KhuêPhường Tứ LiênPhường Xuân LaPhường Yên Phụ</value>
      <webElementGuid>ac2e1a01-2101-4ee5-ac42-a575b27bea70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAddressForm_WardId&quot;)</value>
      <webElementGuid>44ec45c8-fff6-4e67-b92a-273dd220e15d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NewAddressForm_WardId']</value>
      <webElementGuid>9731640c-8e81-47fe-b801-8cd6b5efca8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step']/div[3]/div/div[6]/div/select</value>
      <webElementGuid>1119cf4d-8f01-4e20-b9e4-fdbacf46919c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>f4d63ace-cc69-45a8-a171-7347e1ef754e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>d981edb5-205e-4744-8594-619011738bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>222fd909-99b0-428b-8249-7da5e8de7eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NewAddressForm_WardId' and @name = 'NewAddressForm.WardId' and (text() = 'Chọn Phường/XãPhường BưởiPhường Nhật TânPhường Phú ThượngPhường Quảng AnPhường Thụy KhuêPhường Tứ LiênPhường Xuân LaPhường Yên Phụ' or . = 'Chọn Phường/XãPhường BưởiPhường Nhật TânPhường Phú ThượngPhường Quảng AnPhường Thụy KhuêPhường Tứ LiênPhường Xuân LaPhường Yên Phụ')]</value>
      <webElementGuid>54b0490b-39f5-4ccd-b6ff-1af070283d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
