<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Chn PhngXTh trn Quc OaiX Cn HuX Cng _020aa4</name>
   <tag></tag>
   <elementGuidId>e80861bd-20b9-49fd-9295-fdfa10621502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NewAddressForm_WardId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewAddressForm_WardId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8c12d4c6-efbf-4e46-9ab1-885262ad94f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewAddressForm_WardId</value>
      <webElementGuid>7a40b7b7-e743-47da-8221-72b531abb171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAddressForm.WardId</value>
      <webElementGuid>d674f30f-d7e3-4588-8517-3b719418a5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn Phường/XãThị trấn Quốc OaiXã Cấn HữuXã Cộng HòaXã Đại ThànhXã Đồng QuangXã Đông XuânXã Đông YênXã Hòa ThạchXã Liệp TuyếtXã Nghĩa HươngXã Ngọc LiệpXã Ngọc MỹXã Phú CátXã Phú MãnXã Phượng CáchXã Sài SơnXã Tân HòaXã Tân PhúXã Thạch ThánXã Tuyết NghĩaXã Yên Sơn</value>
      <webElementGuid>661a5227-647d-4ef3-a588-b014019405f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAddressForm_WardId&quot;)</value>
      <webElementGuid>fb1c5fdb-d3ff-422a-aca1-3f2fe14edc38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NewAddressForm_WardId']</value>
      <webElementGuid>23064858-175f-41f9-b463-d468927c7696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step']/div[3]/div/div[6]/div/select</value>
      <webElementGuid>e07a7221-9907-435c-9393-8ca144ac70f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>245bd72a-651c-4672-897b-ea6c8f287cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>7c524385-759e-44ef-ac98-51a994b3a2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>fae7d84c-ff4b-4823-832e-070d1db33f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NewAddressForm_WardId' and @name = 'NewAddressForm.WardId' and (text() = 'Chọn Phường/XãThị trấn Quốc OaiXã Cấn HữuXã Cộng HòaXã Đại ThànhXã Đồng QuangXã Đông XuânXã Đông YênXã Hòa ThạchXã Liệp TuyếtXã Nghĩa HươngXã Ngọc LiệpXã Ngọc MỹXã Phú CátXã Phú MãnXã Phượng CáchXã Sài SơnXã Tân HòaXã Tân PhúXã Thạch ThánXã Tuyết NghĩaXã Yên Sơn' or . = 'Chọn Phường/XãThị trấn Quốc OaiXã Cấn HữuXã Cộng HòaXã Đại ThànhXã Đồng QuangXã Đông XuânXã Đông YênXã Hòa ThạchXã Liệp TuyếtXã Nghĩa HươngXã Ngọc LiệpXã Ngọc MỹXã Phú CátXã Phú MãnXã Phượng CáchXã Sài SơnXã Tân HòaXã Tân PhúXã Thạch ThánXã Tuyết NghĩaXã Yên Sơn')]</value>
      <webElementGuid>5041edc9-9de1-4ecb-b489-952e5c483182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
