<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Chn QunHuynHuyn Ba VHuyn Chng MHuyn _0c3e00</name>
   <tag></tag>
   <elementGuidId>c1c4b80a-1a71-4aed-b146-c8d81d4a7434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NewAddressForm_DistrictId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewAddressForm_DistrictId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>68619c5a-1d1b-43d5-bedd-c1312098193c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewAddressForm_DistrictId</value>
      <webElementGuid>202ae483-01bc-4816-8e09-d9d017228ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewAddressForm.DistrictId</value>
      <webElementGuid>b7d0d2d5-713a-4546-9206-4a108cbd15ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn Quận/HuyệnHuyện Ba VìHuyện Chương MỹHuyện Đan PhượngHuyện Đông AnhHuyện Gia LâmHuyện Hoài ĐứcHuyện Mê LinhHuyện Mỹ ĐứcHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìHuyện Thường TínHuyện Ứng HòaQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyQuận Đống ĐaQuận Hà ĐôngQuận Hai Bà TrưngQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênQuận Nam Từ LiêmQuận Tây HồQuận Thanh XuânThị xã Sơn Tây</value>
      <webElementGuid>892cf666-ecce-4a8b-9c21-749f0f49fdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAddressForm_DistrictId&quot;)</value>
      <webElementGuid>a2005419-7096-4dd2-a3fb-1882a2e734de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NewAddressForm_DistrictId']</value>
      <webElementGuid>79da6e05-2dda-44b8-b3f2-f016f2d6b8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-step']/div[3]/div/div[5]/div/select</value>
      <webElementGuid>e2d51cc3-a9a9-439b-b244-ec5b742c52ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>457a4db3-4773-41a0-a3dc-7c6421964f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>e0a60d94-9587-480e-bd42-b521122c2da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>84821f6e-7c5a-4797-995c-95df9d9d95f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NewAddressForm_DistrictId' and @name = 'NewAddressForm.DistrictId' and (text() = 'Chọn Quận/HuyệnHuyện Ba VìHuyện Chương MỹHuyện Đan PhượngHuyện Đông AnhHuyện Gia LâmHuyện Hoài ĐứcHuyện Mê LinhHuyện Mỹ ĐứcHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìHuyện Thường TínHuyện Ứng HòaQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyQuận Đống ĐaQuận Hà ĐôngQuận Hai Bà TrưngQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênQuận Nam Từ LiêmQuận Tây HồQuận Thanh XuânThị xã Sơn Tây' or . = 'Chọn Quận/HuyệnHuyện Ba VìHuyện Chương MỹHuyện Đan PhượngHuyện Đông AnhHuyện Gia LâmHuyện Hoài ĐứcHuyện Mê LinhHuyện Mỹ ĐứcHuyện Phú XuyênHuyện Phúc ThọHuyện Quốc OaiHuyện Sóc SơnHuyện Thạch ThấtHuyện Thanh OaiHuyện Thanh TrìHuyện Thường TínHuyện Ứng HòaQuận Ba ĐìnhQuận Bắc Từ LiêmQuận Cầu GiấyQuận Đống ĐaQuận Hà ĐôngQuận Hai Bà TrưngQuận Hoàn KiếmQuận Hoàng MaiQuận Long BiênQuận Nam Từ LiêmQuận Tây HồQuận Thanh XuânThị xã Sơn Tây')]</value>
      <webElementGuid>59a75315-d54c-429d-a52d-220e8559b40e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
