<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bn_lozad</name>
   <tag></tag>
   <elementGuidId>e0e1016a-59d0-45d9-a4c5-d3fd6fcfb07f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-a26f11ca3e5ccb42']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.img-scale.product-item-69.ga-item > img.lozad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3400b1f-f625-49e7-8f25-803891f6e754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>1cbf9722-a22b-4f82-90da-bf4075033f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/may-rua-mat-emmie-premium-facial-cleansing-brush-dat-chung-nhan-fda-sky-blue.png</value>
      <webElementGuid>257f5507-0292-41b5-81db-6f63fe8bbefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/may-rua-mat-emmie-premium-facial-cleansing-brush-dat-chung-nhan-fda-sky-blue.png</value>
      <webElementGuid>14a6a395-5543-4abf-8837-5159e10cfd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue</value>
      <webElementGuid>3ad05920-305b-4c06-a1d5-4bc3c1989f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e43dde53-725b-48f2-af8c-41d70fe7c19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-f6325131074133027&quot;)/div[@class=&quot;swiper-slide&quot;]/div[@class=&quot;product-square-item&quot;]/div[@class=&quot;product-image ga-object&quot;]/a[@class=&quot;img-scale product-item-69 ga-item&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>0ab15989-ebd5-41b7-ab97-8b45b2c3350d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-f6325131074133027']/div[3]/div/div/a/img</value>
      <webElementGuid>b2462396-841e-446b-ba6a-327231e5d7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue'])[3]</value>
      <webElementGuid>8d7ad1fb-8410-4d9e-a1ba-327fcc421c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/div/div/a/img</value>
      <webElementGuid>8510b15b-a541-40b6-8ec9-d2239d013f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.happyskin.vn/media/26/may-rua-mat-emmie-premium-facial-cleansing-brush-dat-chung-nhan-fda-sky-blue.png' and @alt = 'Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue']</value>
      <webElementGuid>8a9a2f82-9a4e-4e94-91e6-30e5d22bc221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-1aa2e57792b3bf7b']/div[3]/div/div/a/img</value>
      <webElementGuid>dc66c7f0-0ee3-42be-b5d9-e2824069431c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue']</value>
      <webElementGuid>374b4bb0-4150-43ea-a1f5-61354a757b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a/img</value>
      <webElementGuid>7cc86223-da8e-4655-8c82-954507410f66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
