<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Xemthm_lozad</name>
   <tag></tag>
   <elementGuidId>01ccca56-01dc-4b18-87e8-4b5e043ed4df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.img-scale.product-item-44.ga-item > img.lozad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@class='img-scale product-item-69 ga-item']//img[@alt='Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a86a93a1-0e5a-48ac-bab4-6b246b241d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>c312197a-e16c-41f2-b984-2774fa04cbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-wild-iris.webp</value>
      <webElementGuid>d50f4617-552c-416b-b034-9ca90d2861bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-wild-iris.webp</value>
      <webElementGuid>1bb870a0-fd21-4b03-96a1-f4fc76012801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Wild Iris</value>
      <webElementGuid>24480412-2908-4df7-90eb-e2dda8a4a903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff7546e8-3f7c-407c-b596-2e69d86f1917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-a26f11ca3e5ccb42&quot;)/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;product-square-item&quot;]/div[@class=&quot;product-image ga-object&quot;]/a[@class=&quot;img-scale product-item-44 ga-item&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>81d2aeb2-361f-4c71-b8ef-60c74e3d43cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-a26f11ca3e5ccb42']/div/div/div/a/img</value>
      <webElementGuid>25c013f6-e023-41ce-ac34-fc7d47b069d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Wild Iris']</value>
      <webElementGuid>5bc15b86-6f7e-4a4e-8891-84190fe166fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/a/img</value>
      <webElementGuid>2d103938-1f82-41fc-97db-701fa2f0f1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-wild-iris.webp' and @alt = 'Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Wild Iris']</value>
      <webElementGuid>b54d2a7a-295c-4104-8dff-2f848d13aaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-e82c10a1179e24bcb']/div[3]/div/div/a/img</value>
      <webElementGuid>cca285d1-666e-4d90-bbd6-ec4c8fd50329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue']</value>
      <webElementGuid>2ec99439-3412-4235-8ffe-824bc141ad88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/div/div/a/img</value>
      <webElementGuid>254aa839-85db-473a-b948-0fb9172ea687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.happyskin.vn/media/26/may-rua-mat-emmie-premium-facial-cleansing-brush-dat-chung-nhan-fda-sky-blue.jpg' and @alt = 'Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue']</value>
      <webElementGuid>1cf8bb0c-50b2-498f-8b35-83cd00edfb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-6dc31a0ac8f989cd']/div[3]/div/div/a/img</value>
      <webElementGuid>802d5700-617f-4597-aa24-7af901e3c7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-5dc9f462a5ad379f']/div[3]/div/div/a/img</value>
      <webElementGuid>b7a018fa-4ac1-4139-b13d-4a455daaf728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-5cf4e55e159dbff2']/div[3]/div/div/a/img</value>
      <webElementGuid>b0763961-3862-4ad9-a4e5-7fc09d313cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-55de69dcbe110c6c4']/div[3]/div/div/a/img</value>
      <webElementGuid>49ff2aab-80d1-4d68-b5eb-3ef3d5c18be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-a6b2075c4ecb10c98']/div[3]/div/div/a/img</value>
      <webElementGuid>bbaa318b-addf-404f-923d-33dd58c9e8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Máy Rửa Mặt Emmié Premium Facial Cleansing Brush - Đạt Chứng Nhận FDA - Sky Blue'])[2]</value>
      <webElementGuid>8053e6d2-91af-49c0-94d9-2679ce0c8195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/div/div/div/div/div[3]/div/div/a/img</value>
      <webElementGuid>7173651e-27c4-4e8c-abe1-7144589c1021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-c2b98d4365f6dd71']/div[3]/div/div/a/img</value>
      <webElementGuid>7009be51-d8bc-496b-89fa-a02fea229bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-c9b7d3a6ef9fe8c2']/div[3]/div/div/a/img</value>
      <webElementGuid>dadc139e-af61-4e26-8e3f-ff39a195cf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-c83f4237991f3372']/div/div/div/a/img</value>
      <webElementGuid>44f58a12-4b84-48a7-9c6e-b532022abbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-3c24058a129c93d2']/div/div/div/a/img</value>
      <webElementGuid>89a12c68-3b1e-40cd-bc7e-743dca7210be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
