<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bn_lozad_1</name>
   <tag></tag>
   <elementGuidId>0a039890-77b6-4eda-8132-f4a0606ee222</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-2d1f16956178232f']/div[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.img-scale.product-item-33.ga-item > img.lozad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>46e54c72-6fd3-4c40-a500-e00b4c1d5029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>404276b0-5df9-44a5-8f6e-fccc95d6619c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-peachy-love.webp</value>
      <webElementGuid>d64ecab1-de7d-4727-8d4c-24be6cfd3733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-peachy-love.webp</value>
      <webElementGuid>1fcfb41f-ea7c-4918-b9c9-8c0180ffa10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Peachy Love</value>
      <webElementGuid>93ec83b4-03a8-4c8f-aa9a-bc5a2f724544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc3b8ff6-3777-44ec-aca6-942792e2e1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-2d1f16956178232f&quot;)/div[@class=&quot;swiper-slide swiper-slide-next&quot;]/div[@class=&quot;product-square-item&quot;]/div[@class=&quot;product-image ga-object&quot;]/a[@class=&quot;img-scale product-item-33 ga-item&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>9243024b-a162-4d47-914e-56c9654a65da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-2d1f16956178232f']/div[2]/div/div/a/img</value>
      <webElementGuid>cd930b0a-b970-4193-ad82-581b4e68ef03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Peachy Love']</value>
      <webElementGuid>2642b0ae-e195-4761-9a34-fdf3ff2990e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/a/img</value>
      <webElementGuid>f8a89c8a-a9c4-4abb-b54e-be3a3a141152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-peachy-love.webp' and @alt = 'Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Peachy Love']</value>
      <webElementGuid>f8673316-efba-4094-8d87-81313120f147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
