<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bn chy_lozad</name>
   <tag></tag>
   <elementGuidId>77d5a6f3-9e15-4483-832d-75b8479788e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-8f452d09ae3a7611']/div/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swiper-wrapper-8f452d09ae3a7611 > div.swiper-slide.swiper-slide-active > div.product-square-item > div.product-image.ga-object > a.img-scale.ga-item > img.lozad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>34d0df28-9cb1-42d5-8479-2f9194d4026e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>d3cb0521-7bd0-4133-8d71-f0b802e9f9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-wild-iris.webp</value>
      <webElementGuid>704422c3-5a83-4553-b516-077b4c01bc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-wild-iris.webp</value>
      <webElementGuid>df5f9831-4f08-472d-ac54-f38c3a1c12ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Wild Iris</value>
      <webElementGuid>0607e3d1-9312-4d25-b8f8-5619e9aade5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>958583b9-733b-452a-967b-64ffc3e20785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-8f452d09ae3a7611&quot;)/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;product-square-item&quot;]/div[@class=&quot;product-image ga-object&quot;]/a[@class=&quot;img-scale ga-item&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>2c9965f8-6a0a-475b-a603-14470b65ac80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-8f452d09ae3a7611']/div/div/div/a/img</value>
      <webElementGuid>462ed6af-3944-4d89-b455-be479e356786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Wild Iris'])[2]</value>
      <webElementGuid>10ae3985-f917-4ea7-9a5e-996877c14667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div/div/div/div/div/div/div/div/div/a/img</value>
      <webElementGuid>32867ac4-85a7-4d12-933c-e5cf9dd53460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.happyskin.vn/media/26/sua-tam-dat-set-ngua-mun-acne-free-body-clay-wash-emmie-250ml-mui-huong-wild-iris.webp' and @alt = 'Sữa Tắm Đất Sét Ngừa Mụn Acne-Free Body Clay Wash Emmié 250ml Mùi Hương: Wild Iris']</value>
      <webElementGuid>98061d95-8b76-4adc-a6fd-6d27e0cfaa13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
