<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qun mt khu_query</name>
   <tag></tag>
   <elementGuidId>99b6317e-4192-48de-b3a6-43842751013b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Query</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Query']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7da2c75c-c465-42e3-8e2b-2b0936aa845a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchinput search-input-main</value>
      <webElementGuid>552098f3-bb1a-4a7c-9ba9-66248ebadaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e23c4f6f-ee6a-4cad-a9e4-73541cf94c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>0ca47a13-4e0f-4e70-989b-af36c3a68dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm kiếm</value>
      <webElementGuid>d8f6912a-9a27-4271-8519-bf5f0ccb2c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Query</value>
      <webElementGuid>ec1ff5fa-a4c3-4523-b803-db30b6c5030e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Query&quot;)</value>
      <webElementGuid>cfcaa796-c696-4802-b5aa-83b0aae7aa17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Query']</value>
      <webElementGuid>45eee446-8ec7-4d68-9f7e-b831f9405c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>dc5f1011-1047-47a4-9edc-39d06e5c24f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'query' and @placeholder = 'Tìm kiếm' and @id = 'Query']</value>
      <webElementGuid>6efb2c99-2d7a-4ce5-a45f-b5968de0b309</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
